config/routes.rb
CommentsApp::Application.routes.draw do |map|
  resources :users
map.connect '/comments/update', :controller => 'comments', :action => 'update'
map.connect '/comments/more', :controller => 'comments', :action => 'more'
match 'users/:id/edit' => 'users#edit'
  resources :comments
  root :to => "comments#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :global_vars 

  def global_vars
    @app_id = "138505499545847"
    @app_secret = "703cb69c29c98ce621e01ee7b3c23e17"
    @app_url =  "http://apps.facebook.com/vickipedia"
    @redirect_url = "http://localhost:3000/"
    # @redirect_url = "http://sociopath.railsplayground.net/session/create"
    @perms = "read_stream"
    @authorize_url = "https://www.facebook.com/dialog/oauth?client_id=138505499545847&redirect_uri=#{@redirect_url}&scope=#{@perms}&display=page"
  end

  def session_login
    logger.info("Inside session login..........")
    session[:at]=nil
    respond_to do |format|
      format.html # index.html.erb
      format.rss
    end    
  end

  def session_new
    logger.info("inside session_new")
    session[:at]=nil
    render :controller => "comment", :action => "session_login" and return
  end

  def session_authenticator
    
    @authenticator ||= Mogli::Authenticator.new(@app_id,
      @app_secret,
      @redirect_url)
  end

  def session_create
    #session[:at] = nil
    if params[:code].nil? and session[:at].nil?
      # logger.info("hello............." )
      session_new
    else
      if !session[:at].nil?
        return #  index #     render :controller=>"comment" , :action => "index"
      else
        #     logger.info("create inside..............................." + params[:code])
        mogli_client = Mogli::Client.create_from_code_and_authenticator(params[:code],session_authenticator)
        logger.info("inside creae")
        session[:at]=mogli_client.access_token
        @access_tok = session[:at]
        logger.info("inside creae.............." + session[:at])
        #index
      end
    end
  end

  def index
    #session[:at]=nil
    logger.info("index..............")
    #session_create
    if params[:code].nil? and session[:at].nil?
      # logger.info("hello............." )
      session[:at]=nil
      render :controller => "comment", :action => "session_login" and return
    else
      if session[:at].nil?
        #  index #     render :controller=>"comment" , :action => "index"

        #  logger.info("create inside..............................." + params[:code])
        mogli_client = Mogli::Client.create_from_code_and_authenticator(params[:code],session_authenticator)
        logger.info("inside creae")
        session[:at]=mogli_client.access_token
        @access_tok = session[:at]
        logger.info("inside creae.............." + session[:at])
        #index
        redirect_to @app_url and return
      end
    end
    #session_create
   
    if(!session[:at])
      redirect_to "/comments/session_login" and return
    end
    logger.info("entered index :) ...." + session[:at])
    begin
      user = Mogli::User.find("me",Mogli::Client.new(session[:at]))
    rescue Mogli::Client::OAuthException => exc
      logger.error("Message for the log file #{exc.message}")
      session[:at]=nil;
      redirect_to(:action => 'index') and return

    end
    @user = user
    logger.info("iiiiiindex.............ha ha")
    unless User.exists?(:extra2 => @user.id)
      User.create(:name => @user.name ,:access_token => session[:at] , :email => @user.name , :extra1 => @user.square_image_url, :extra2 => @user.id)
     
    end
  
    @comments = Comment.find(:all, :order =>'created_at' , :limit => 20)

    if @comments.nil?
      @last_comment_time =0;
      @first_comment_time =0;
    else
      @last_comment_time=@comments.last.created_at;
      @first_comment_time = @comments.first.created_at ;
    end
    #  logger.info(@last_comment_time)
    #  logger.info(@first_comment_time)
    
    #logger.info(@last_comment.created_at.to_s);
    
    respond_to do |format|
      format.html # index.html.erb
      format.rss
    end
  end
  
  def create
    @tempuser = User.where(:extra2 => params[:comment][:user_id])

    ## CHECK FOR BLOCKED TIME AND CURRENT TIME ##
    if @tempuser.first.blocked == "1" #and @tempuser.first.blocked_time+@tempuser.first.blocked_period  <
      #blocked users
      flash[:notice] = "sorry you have been blocked" and return
    else
      if params[:comment][:content].lstrip.rstrip == ""
        flash[:notice] = "No Blank commenting"
      else
        if Comment.find(:first , :conditions => ["user_id = ?",params[:comment][:user_id]] , :order => 'created_at desc').content == params[:comment][:content].lstrip.rstrip
          flash[:notice] = "Your Last comment was also same"
      else
        @comment = Comment.create!(:content => params[:comment][:content].lstrip.rstrip , :user_id => params[:comment][:user_id])
        @user = Mogli::User.find("me",Mogli::Client.new(session[:at]))
        # @user_id = (User.where(:extra2 => params[:comment][:user_id])).first.name
        # logger.info(@user1.first.name+"////////////////////////////");
        #logger.info("--------------------------")
        flash[:notice] = "Thanks for commenting!"
      end
      end
    end

    respond_to do |format|
      format.html { redirect_to comments_path }
      format.js 
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_path }
      format.js
    end
  end


  #add we should not take the comments posted by him coz it ll already be present there
  def update
    logger.info(params[:comment][:last_time])
    @user = Mogli::User.find("me",Mogli::Client.new(session[:at]))
    if params[:comment][:last_time]== "0"
      @comments = Comment.find(:all,:conditions => ["user_id != ?",@user.id] ,:order =>'created_at' , :limit => 20)
      logger.info("last_comment_time")
      if @comments.nil?
        @last_comment_time = "0";
        logger.info(@last_comment_time)
      else
        @last_comment_time=@comments.last.created_at;
        logger.info(@last_comment_time)
      end
      logger.info("|||||||||||||||||||")
    else
      @last_time = Time.parse(params[:comment][:last_time])
      logger.info(@last_time)
      logger.info("++++++++++")
      #   @comments = Comment.all

      ## SORT BY CREATEDAT ##
      #@comments = Comment.where('created_at > ?',@last_time)
      @comments = Comment.find(:all, :conditions => ["created_at > ? and user_id != ?",@last_time,@user.id] ,:order => 'created_at')
      @last_comment_time = @comments.last.created_at
    end
    respond_to do |format|
      format.html { redirect_to comments_path }
      format.js
    end
  end

  def more
    logger.info(params[:comment][:first_time])
    @user = Mogli::User.find("me",Mogli::Client.new(session[:at]))
    if params[:comment][:first_time]== "0"
      @comments = Comment.find(:all,:conditions => ["user_id != ?",@user.id] ,:order =>'created_at desc' , :limit => 20)
      logger.info("first_comment_time")
      if @comments.nil?
        @first_comment_time = "0";
        logger.info(@first_comment_time)
      else
        @first_comment_time=@comments.first.created_at;
        logger.info(@first_comment_time)
      end

      logger.info("|||||||||||||||||||")
    else
      @last_time = Time.parse(params[:comment][:first_time])
      logger.info(@first_time)
      logger.info("++++++++++")
      #   @comments = Comment.all

      ## SORT IN REVERSE ##
      #@comments = Comment.where('created_at < ?',@last_time)
      @comments = Comment.find(:all, :conditions => ["created_at < ? and user_id != ?",@first_time,@user.id] ,:order => 'created_at desc' ,:limit => 20)
      @last_comment_time = @comments.first.created_at
    end
    
    respond_to do |format|
      format.html { redirect_to comments_path }
      format.js
    end
  end

 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>

  <span class="dateandoptions" >
    <small>  <%=time_ago_in_words(comment.created_at)%> ago </small><br />

    <% @temp = (User.where(:extra2 => comment.user_id)).first %>
    <%  @profile_pic = @temp.extra1  %>

    <!-- block user -->
    <% if @user.id == "694081777" || @user.id == "1131990070" %>

    <!-- Add more to check the time -->
    <% if @temp.blocked == "1" %>
        <%= link_to 'unblock' , edit_user_path(comment.user_id) , :method => :edit , :class => "block"  %>
      <% else %>
        <%= link_to 'block' , edit_user_path(comment.user_id) , :method => :edit , :class => "block"  %>
      <% end %>
    <% end %>

    <!-- Delete link -->
    <!-- Admins have special privilages to delete messages Rajesh , Vignesh -->

    <% if (comment.user_id) == @user.id || @user.id == "694081777" || @user.id == "1131990070" %>
      <%= link_to 'Delete', comment_path(comment), :method => :delete, :class => "delete", :remote => true  %>

    <% end %>
    <!-- End of Delete link -->
  </span>
  <!-- Profilepic-->
  <a href="http://wwww.facebook.com/profile.php?id=<%=comment.user_id%>" target="_blank" > <img src= <%=@temp.extra1%>> </img> </a>
  <!-- End of profile pic -->
  <b><a href="http://wwww.facebook.com/profile.php?id=<%=comment.user_id%>" target="_blank" style="text-decoration:none;" ><%= @temp.name %> </a>: </b>
  <%= content_tag(:p, comment.content, :class => "comment-body") %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user1_id %><br />
    <%= f.text_field :user1_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
/* Insert a notice between the last comment and the comment form */
$("#comment-notice").html('<div class="flash notice"><%= escape_javascript(flash.delete(:notice)) %></div>');

/* Replace the count of comments 
$("#comments_count").html("<%= pluralize(Comment.count, 'Comment') %>");
*/
/* Add the new comment to the bottom of the comments list */

<% unless @comment.nil? %>
$("#comments").append("<%= escape_javascript(render(@comment))  %>");

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

/* Reset the comment form */
$("#new_comment")[0].reset();
<% end %>

app/views/comments/destroy.js.erb
/* Eliminate the comment by fading it out */
$('#comment_<%= @comment.id %>').fadeOut();
/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(Comment.count, 'Comentari') %>");

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<head>
  <script type="text/javascript">
    window.onload = function() {
      //delay_update();
    }
  </script>

</head>

<!-- number of comments
<span id="comments_count"><%= pluralize(@comments.count, "Comment") %></span>
-->
<!--
<iframe id='upload_frame' name="upload_frame" >
  <p>Your browser does not support iframes.</p>
</iframe>
-->

<div id="comments" class="chatbox" style="max-height:300px;overflow:auto;">
  <%= render :partial => @comments, :locals => { :list => true } %>
</div>

<div id="panditoftheday">

</div>

<!-- Widget starts here -->
<!-- No commentry but fast 
<script type="text/javascript" src="http://cdn.widgetserver.com/syndication/subscriber/InsertWidget.js"></script><script type="text/javascript">if (WIDGETBOX) WIDGETBOX.renderWidget('0f63beb3-c61b-496d-95f5-5781082b8e6f');</script><noscript>Get the <a href="http://www.widgetbox.com/widget/live-cricket-scores-espn-star-sports">Live Cricket Scores</a> widget and many other <a href="http://www.widgetbox.com/">great free widgets</a> at <a href="http://www.widgetbox.com">Widgetbox</a>! Not seeing a widget? (<a href="http://docs.widgetbox.com/using-widgets/installing-widgets/why-cant-i-see-my-widget/">More info</a>)</noscript>
-->
<!-- Damn slow did not even load 
<script type="text/javascript" src="http://cdn.widgetserver.com/syndication/subscriber/InsertWidget.js"></script><script type="text/javascript">if (WIDGETBOX) WIDGETBOX.renderWidget('a397d63f-1f6d-4ade-8038-e8f4d3a12f4e');</script><noscript>Get the <a href="http://www.widgetbox.com/widget/crickternews-livescorecard-widget">Cricket Live Score Widget from CricketerNews.com</a> widget and many other <a href="http://www.widgetbox.com/">great free widgets</a> at <a href="http://www.widgetbox.com">Widgetbox</a>! Not seeing a widget? (<a href="http://docs.widgetbox.com/using-widgets/installing-widgets/why-cant-i-see-my-widget/">More info</a>)</noscript>
-->
<!-- No commentry but fast and bigger -->
<!--
<script type="text/javascript" src="http://cdn.widgetserver.com/syndication/subscriber/InsertWidget.js"></script><script type="text/javascript">if (WIDGETBOX) WIDGETBOX.renderWidget('24ab7637-b67b-4b95-9a10-320ab485678b');</script><noscript>Get the <a href="http://www.widgetbox.com/widget/cricket-espn-star-sports">Cricket</a> widget and many other <a href="http://www.widgetbox.com/">great free widgets</a> at <a href="http://www.widgetbox.com">Widgetbox</a>! Not seeing a widget? (<a href="http://docs.widgetbox.com/using-widgets/installing-widgets/why-cant-i-see-my-widget/">More info</a>)</noscript>
-->
<!-- Widget ends here -->
<div id="comment-notice"></div>


<%= form_for Comment.new , :remote => true  do |f| %>
  <%= f.hidden_field(:user_id, :value => @user.id )  %>
  <%= f.label :content, "Comment" %><br />
  <%= f.text_area :content, :rows => 2 , :class => "chatbox"%><br />
  <%= f.submit "Add comment" %>
<% end %>

<span id="update_form">
  <% form_for Comment.new , :remote => true , :url => { :action => "update" } do |f| %>
    <%= f.hidden_field(:last_time , :value => @last_comment_time) %>
    <%= f.submit "update chats" , :id => "comment_update" %>
  <% end %>
</span>


<span id="more form">
  <% form_for Comment.new , :remote => true , :url => { :action => "more" } do |f| %>


    <%= f.hidden_field(:first_time , :value => @first_comment_time) %>


    <%= f.submit "more chats" , :id => "more_chats" %>
  <% end %>
</span>

app/views/comments/more.js.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<% if @last_comment_time != "0"  %>
  $("#more_form").html('<%= form_for Comment.new , :remote => true , :url => { :action => "more" } do |f| %> <%= f.hidden_field(:first_time , :value => @first_comment_time) %><%= f.submit "more chats" , :id => "more_chats" %> <% end %>') ;

<% end %>

<%  @comments.each  do |@comment| %>

  /* Add the new comment to the bottom of the comments list */

  <% unless @comment.nil? %>
    $("#comments").prepend("<%= escape_javascript(render(@comment))  %>");

    /* Highlight the new comment */
    $("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

    /* Reset the comment form */
    $("#new_comment")[0].reset();
  <% end %>

<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/session_login.html.erb
<script>

function foo()
{
//window.location = "https://www.facebook.com/dialog/oauth?client_id=138505499545847&redirect_uri=http://sociopath.railsplayground.net/fb/show/&scope=publish_stream,offline_access,email,friends_about_me"
var url = "https://www.facebook.com/dialog/oauth?client_id=138505499545847&redirect_uri=http://localhost:3000/&scope=read_stream&display=page"
//var url = "https://www.facebook.com/dialog/oauth?client_id=138505499545847&redirect_uri=http://sociopath.railsplayground.net/session/create/&scope=read_stream&display=page"
window.top.location = url;
}

</script>

<body onload="foo()">
  <%= logger.info("File is getting rendered") %>
This might take a few seconds. Patience plz... :)!!!
</body>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>User1:</b>
  <%= @comment.user1_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/update.js.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<% if @last_comment_time != "0"  %>
  $("#update_form").html('<%= form_for Comment.new , :remote => true , :url => { :action => "update" } do |f| %> <%= f.hidden_field(:last_time , :value => @last_comment_time) %><%= f.submit "update chats" , :id => "comment_update" %> <% end %>') ;

<% end %>

/* put the HTML for pandit of the day */
<%  @comments.each  do |@comment| %>


  /* Replace the count of comments
  $("#comments_count").html("<%= pluralize(Comment.count, 'Comment') %>");
  */
  /* Add the new comment to the bottom of the comments list */

  <% unless @comment.nil? %>
    $("#comments").append("<%= escape_javascript(render(@comment))  %>");

    /* Highlight the new comment */
    $("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

    /* Reset the comment form */
    $("#new_comment")[0].reset();
  <% end %>

<% end %>